project:
  type: website
  output-dir: docs
  resources:
    - "customer-rate-limit-report/data/*.csv"
    - "datadog-4xx-error-analysis/data/*.csv"

execute:
  freeze: auto

format:
  html:
    embed-resources: true
    toc: true
    theme: cosmo

website:
  title: "My Reports"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: customer-rate-limit-report/customer-rate-limit-report.qmd
        text: Customer Rate Limit Report
      - href: datadog-4xx-error-analysis/datadog-4xx-error-analysis.qmd
        text: Datadog 4XX Error Analysis
